replicas: 1
cpu:
  requests: "100m"
  limits: "8000m"
memory:
  requests: "64Mi"
  limits: "16Gi"
serviceType: ClusterIP
image:
  Name: lsheiba/fast-neural-style
  Tag: latest
persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 16Gi
